### ISSUE TITLE
Fix Orc 1.9.0 regression

### ISSUE THREAD

**Issue by pitrou** [conda-forge/orc-feedstock#64]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Orc 1.9.0 has a bug that prevents compilation for downstream packages (such as Arrow, on a weirdly non-deterministic basis). It would be nice to either include this simple patch, or revert to 1.8.4:
https://github.com/apache/orc/pull/1557

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by pitrou** [comment]
cc @wgtmac @h-vetinari

**Comment by h-vetinari** [comment]
FWIW, I haven't seen problems in conda-forge related to building against or using orc 1.9.0, but happy to help where I can.

**Comment by jakirkham** [comment]
Maybe we can change [the `orc` migration for `1.9.0`]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/6c1fa11631305c47b15965e780bdf45a86712ef6/recipe/migrations/orc190.yaml#L6-L7 ) to [a version addition]( https://github.com/conda-forge/cfep/blob/2409812d68296fcf2e06255687cc7cb085923ffd/cfep-09.md#2-matrix-version-addition-changes ). IOW supporting both 1.8.4 & 1.9.0 for a bit

**Comment by wgtmac** [comment]
> Maybe we can change [the `orc` migration for `1.9.0`](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/6c1fa11631305c47b15965e780bdf45a86712ef6/recipe/migrations/orc190.yaml#L6-L7) to [a version addition](https://github.com/conda-forge/cfep/blob/2409812d68296fcf2e06255687cc7cb085923ffd/cfep-09.md#2-matrix-version-addition-changes). IOW supporting both 1.8.4 & 1.9.0 for a bit

Good to know. It sounds good to me.

**Comment by h-vetinari** [comment]
I would prefer not to. Arrow is already very big, and we have no compilation problems plus a fully passing test suite with 1.9.

@pitrou, do you have these problems with your conda-CI, or elsewhere?

**Comment by pitrou** [comment]
Ah, it appears a workaround was already committed in Arrow:
https://github.com/apache/arrow/commit/377811f47dfbcc57a4fd3b4b90aea96e2d6587fb#diff-9686eae3ba6a285ffa98c72a98ed31abecf6f37734ff86de5d6303279a0e7fd0R1046

Probably those builds which fail didn't have the workaround...

**Comment by h-vetinari** [comment]
OK, that's great to hear. Sounds like we could close this issue then?

**Comment by pitrou** [comment]
Well, it would probably break other people's use of liborc, but it's ok to me if conda-forge doesn't care.

**Comment by h-vetinari** [comment]
> Well, it would probably break other people's use of liborc, but it's ok to me if conda-forge doesn't care.

IIUC correctly it's "just" an API change in 1.9? So whoever wants to use 1.9 builds from conda-forge will have to adapt, but we can't second-guess the orc-developers and their APIs, so that's completely fine IMO.

**Comment by pitrou** [comment]
No, it's a compilation error when using an API that's intended to work.

**Comment by h-vetinari** [comment]
> No, it's a compilation error when using an API that's intended to work. It will be fixed in 1.9.1 / 2.0.0.

OK, thanks for the explanation, now I get what's happening

> It would be nice to either include this simple patch, or revert to 1.8.4: https://github.com/apache/orc/pull/1557

We can backport this patch if anyone else is affected, but I'd prefer to wait for 1.9.1 TBH. Is there a timeline for that already?

**Comment by h-vetinari** [comment]
> I'd prefer to wait for 1.9.1 TBH. Is there a timeline for that already?

@wgtmac, any idea?

**Comment by wgtmac** [comment]
> > I'd prefer to wait for 1.9.1 TBH. Is there a timeline for that already?
> 
> @wgtmac, any idea?

v1.9.1 release is planned in this August.

**Comment by h-vetinari** [comment]
Thanks for the info, that's fine by me. In the context of this issue, I see it as the responsibility of the orc project to fix a regression (and quickly if it's considered serious), not the responsibility of the feedstock to start backporting things. Of course, theory and practice can diverge ;)

**Comment by h-vetinari** [comment]
Seeing that we're now in orc 2.0 and have migrated this across conda-forge, I'm closing this issue as obsolete.
